### ISSUE TITLE
工事中用イラスト描く

### ISSUE THREAD

**Issue by nabe-kurage** [onestop-techbook/gipotal#23]

**Comment by nabe-kurage** [comment]
![イラスト62](https://user-images.githubusercontent.com/38372239/84329049-9a5acf80-abbe-11ea-8e7a-e81e1a3e470a.jpg)

**Comment by nabe-kurage** [comment]
![gipotalイラストサイズ変更](https://user-images.githubusercontent.com/38372239/84330411-44882680-abc2-11ea-963a-b9f52c2860b9.jpg)

**Comment by nabe-kurage** [comment]
宿題
- 塗り残しなくす
- 真ん中位置調整
- 画像透過

**Comment by mottox2** [comment]
ある程度、トリミングで横幅を削ってくれるとうれしみ

**Comment by nabe-kurage** [comment]
画像真ん中（画像下部分の一番とんがった箇所）を意識したら若干右側に空白が大きくできるんですが、その状態で大丈夫でしょうか？
