### ISSUE TITLE
Webランダムリング機能

### ISSUE THREAD

**Issue by ditflame** [onestop-techbook/gipotal#24]
自分の本の属性をタグ付けとかは当然すると思うのですが、同属性のタグのだれかさんの所に飛べます　みたいな機能。

おそらくオンラインになると「これと同じ系統の本を見たいな～」というファジーな要望はあると思うけど、検索したら恐らく検索上位に来るものばかりにアクセスが集中してしまい、オフラインイベントのような「島全部舐める」動きができなくなると思うので、そういう動きをしたいユーザと登録者さんを繋げる仕掛けとして。

**Comment by ykichinomiya** [comment]
共通のタグが付いた本をネットワークグラフで可視化できたら便利かも。
と考えたんですが、それだと表示が細かくなって見にくいですかねぇ…

**Comment by erukiti** [comment]
タグクラウドとか

**Comment by ykichinomiya** [comment]
[BOOTHのトップページ](https://booth.pm/ja)をみると

- 特集
- お気に入り新着
- おすすめ
- カテゴリ
- タグ

となっていて、下に行くほど能動的に探す人向けになってますね。
