### ISSUE TITLE
サイトの利用規約をつくる

### ISSUE THREAD

**Issue by higuyume** [onestop-techbook/gipotal#3]
# やりたいこと
利用規約を作る

**Comment by oyakata2438** [comment]
・情報商材系は、削除、垢BANできるように規約を組む。

疑われる場合は、連絡　→回答なし　→BAN
　　　　　　　　　　　→弁明、見本誌確認→運営判断でBAN可能に。
って感じかな・・・
手動対応だけど、BANの可能性があるってところと、判定手順は書いておきたい。

**Comment by oyakata2438** [comment]
規約テンプレを入れた&情報商材のＢＡＮ規定を追加した。
https://github.com/onestop-techbook/tech-book-portal/commit/8bd6751af5e1fda5b98dc26e6dbe916ac424ab55

**Comment by oyakata2438** [comment]
いったんこれでClose
