### ISSUE TITLE
諸経費とマネタイズについて

### ISSUE THREAD

**Issue by oyakata2438** [onestop-techbook/gipotal#30]
目標

    継続的なマネタイズ(サーバー、ドメイン代)
    初期費用のマネタイズ
    可能ならば、打ち上げ費

案(是非はともかく可能なもの)

    グッズ(手ぬぐい、アクキー、シール、缶バッチ)
    広告
    手数料
    お布施
    ギポタル同人誌

マネタイズしない(=持ち出しでやり続ける)というのもあるか？

**Comment by ykichinomiya** [comment]
企業向けの購入代行サービスはどうでしょうか。
「新人教育で技術同人誌を使いたいけれど経費で買いにくい」というニーズがあるように思えるので。
ちゃんとした雰囲気の領収証を出せればニーズがあるのでは。

**Comment by oyakata2438** [comment]
なる・・・ほど・・・
確かに。

**Comment by ykichinomiya** [comment]
｢今、社内教育に技術同人誌を活用する企業が増えています！｣みたいな。
企業が買ってくれたらサークルのモチベーション的にも嬉しいですし。

**Comment by ditflame** [comment]
他の合同誌の原稿費を充当できるとかであれば充当してほしいなーとは思っています。
