### ISSUE TITLE
サイトに登録した情報を簡単にコピペしたい

### ISSUE THREAD

**Issue by higuyume** [onestop-techbook/gipotal#5]
# やりたいこと
各イベントへ情報を登録するときに、ポータルに記載されている情報をコピーしてペーストするだけで良いようにできると楽ちんだよねー

# 実現方法
ブックマークレートでも良い、chromeの拡張機能で作るとかでも！

**Comment by oyakata2438** [comment]
便利だけど・・イベントごとにフォーマット違うし、
名前とか連絡先とか、表に出てこない情報多いんじゃ・・・

本の紹介をコピペするくらいが関の山では・・・？
