### ISSUE TITLE
Hasura.ioを調べる。

### ISSUE THREAD

**Issue by smatsuda0620** [onestop-techbook/gipotal#8]
- 公式
https://hasura.io/docs/1.0/graphql/manual/index.html

**Comment by smatsuda0620** [comment]
完全に理解した。（Getting startedやってみた

**Comment by smatsuda0620** [comment]
Auth... う、頭が。
Authマン助けてくれー。

https://hasura.io/docs/1.0/graphql/manual/auth/index.html

**Comment by mottox2** [comment]
managedなサービスができた模様
https://hasura.io/blog/announcing-hasura-cloud-managed-graphql-for-your-database-and-services/
